print('    /|')
print('   / |')
print('  /  |')
print(' /   |')
print('/____|') 
print('_____________')
print('|            |')
print('|            |')
print('|            |')
print('|____________|')
